### PR TITLE
add support for ioredis

### LINKED ISSUE #30: ioredis support
Would it be possible to add support for [ioredis](https://github.com/luin/ioredis) instrumentation in addition to the recently-added support for [node_redis](https://github.com/NodeRedis/node_redis)?

### PR DESCRIPTION
**Pull request by schmod**
Adds instrumentation for the [ioredis](https://github.com/luin/ioredis) Redis client.

Closes #30.

### CODE REVIEW

**Comment by bripkens** [comment]
Thank you for this great PR @schmod ❤️ ! I manually merged it with some changes to adapt it to our guidelines (admittedly not documented so you couldn't have known). Commit: https://github.com/instana/nodejs-sensor/commit/327750e01308b83c67afe57195e1056c8df18d26

Thanks again!

**Comment by bripkens** [comment]
Once the tests are executed & green on travis, I will release your changes.

**Comment by schmod** [comment]
@bripkens I think you conflated `multi` and `pipeline` in your commit -- ioredis has both.

**Comment by bripkens** [comment]
Ah, I was wondering why you added this and why the tests were still green after I removed this condition. We will need additional tests for pipeline and then also adapt the implementation accordingly.

**Comment by schmod** [comment]
You can probably just reuse the `multi` test -- the semantics are exactly the same.

**Comment by bripkens** [comment]
The semantics are slightly different as I understand it. `multi` defines a Redis [transaction](https://redis.io/topics/transactions). So one failed command will fail the entire transaction. Because of this, it makes sense to model a transaction as a single span.

I understand `pipeline` as a why to optimize predominantly for [network latency](https://redis.io/topics/pipelining). Because of this, I think that commands should be handled differently when pipelined. More specifically, I do not think that they should be aggregated into a single span (as each command has its own [error state](https://github.com/luin/ioredis#pipelining)).

**Comment by bripkens** [comment]
Alternatively, pipeline commands could be modeled as a single span, but the batch and error count semantics (`ec` field in the span) must be respected.

**Comment by bripkens** [comment]
I will refrain from releasing this for now. We need at least a test to verify that pipelining still works.

**Comment by bripkens** [comment]
Taking of this now.

**Comment by bripkens** [comment]
Follow up in: https://github.com/instana/nodejs-sensor/pull/34

**Pull request closed without merging**
